title_size = 18
label_size = 16
tick_size = 14
legend_size = 14
linewidth = 1.8
false_zero = 10
recall_ylim = 0.15
time_ylim = 1.1
format = 'png'

[colors]
full = 'blue'
abbr = 'red'
ai = 'green'
ai_alpha = 0.1
